import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

// Generated by scripts/split-content.mjs from content/*.md. Never edit src/content/generated by hand.
const base = (dir: string) => glob({ pattern: '**/*.md', base: `./src/content/generated/${dir}`, generateId: ({ entry }) => entry.replace(/\.md$/, '') });

const common = ({ image }: { image: () => z.ZodTypeAny }) => ({
  title: z.string(),
  lang: z.string(),
  translationKey: z.string(),
  summary: z.string(),
  lede: z.string().optional(),
  number: z.string().nullable().optional(),
  order: z.number(),
  cover: image().optional(),
  coverIllustration: z.boolean().default(false), // AI-generated cover: captioned as an illustration
  tags: z.array(z.string()).default([]),
  published: z.coerce.date().nullable().optional(),
  updated: z.coerce.date().nullable().optional(),
  comments: z.boolean().default(true),
  map: z.boolean().default(false),
  draft: z.boolean().default(false),
  featured: z.boolean().default(false),
  // Reserved for later (FR-33)
  author: z.string().optional(),
  series: z.string().optional(),
  seriesOrder: z.number().optional(),
  video: z.string().optional(),
  downloads: z.array(z.object({ label: z.string(), url: z.string() })).optional(),
});

const projects = defineCollection({
  loader: base('projects'),
  schema: (ctx) => z.object({
    ...common(ctx),
    sector: z.string(),
    secondarySectors: z.array(z.string()).default([]),
    client: z.string().nullish(),
    location: z.string().nullish(),
    year: z.union([z.number(), z.string()]).nullable().optional(),
    role: z.string().nullish(),
    methods: z.array(z.string()).default([]),
    outcome: z.string().nullish(),
    regions: z.array(z.object({ name: z.string(), lon: z.number(), lat: z.number() })).default([]),
    glance: z.array(z.object({ label: z.string(), value: z.string() })).default([]),
  }),
});

const posts = defineCollection({
  loader: base('posts'),
  schema: (ctx) => z.object({ ...common(ctx), categories: z.array(z.string()).min(1) }),
});

const pages = defineCollection({ loader: base('pages'), schema: (ctx) => z.object(common(ctx)) });

export const collections = { projects, posts, pages };
